import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const chatProviderOptions = ['mock', 'openai', 'gemini', 'azure', 'local'];
const speechProviderOptions = ['mock', 'deepgram', 'gemini', 'azure', 'local', 'browser'];
function ProviderEditor({ label, config, onChange, options }) {
    return (_jsxs("div", { className: "space-y-2 border border-base-300 rounded-box p-3", children: [_jsx("h4", { className: "font-semibold", children: label }), _jsx("select", { className: "select select-bordered w-full", value: config.type, onChange: (e) => onChange({ ...config, type: e.target.value }), children: options.map((p) => _jsx("option", { value: p, children: p }, p)) }), _jsx("input", { className: "input input-bordered w-full", placeholder: "API key", value: config.apiKey || '', onChange: (e) => onChange({ ...config, apiKey: e.target.value }) }), _jsx("input", { className: "input input-bordered w-full", placeholder: "Base URL / region", value: config.baseUrl || '', onChange: (e) => onChange({ ...config, baseUrl: e.target.value }) }), _jsx("input", { className: "input input-bordered w-full", placeholder: "Model", value: config.model || '', onChange: (e) => onChange({ ...config, model: e.target.value }) })] }));
}
export function SettingsPanel({ open, settings, onClose, onSave }) {
    if (!open)
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-black/50 z-50 flex justify-end", children: _jsxs("div", { className: "w-full max-w-md bg-base-100 h-full p-4 overflow-y-auto space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("h3", { className: "text-xl font-bold", children: "Settings" }), _jsx("button", { className: "btn btn-sm", onClick: onClose, children: "Close" })] }), _jsx(ProviderEditor, { label: "Chat provider", options: chatProviderOptions, config: settings.chat, onChange: (chat) => onSave({ ...settings, chat }) }), _jsx(ProviderEditor, { label: "Speech-to-text provider", options: speechProviderOptions, config: settings.stt, onChange: (stt) => onSave({ ...settings, stt }) }), _jsx(ProviderEditor, { label: "Text-to-speech provider", options: speechProviderOptions, config: settings.tts, onChange: (tts) => onSave({ ...settings, tts }) }), _jsx("textarea", { className: "textarea textarea-bordered w-full", rows: 4, value: settings.systemPrompt, onChange: (e) => onSave({ ...settings, systemPrompt: e.target.value }) })] }) }));
}
